### ISSUE TITLE
ifdef for external SHA-256 implementation

### ISSUE THREAD

**Issue by alexJiangSierra** [cisco/hash-sigs#12]
Hi,
Could you add an #ifdef to sha256.h to allow for external implementations?  Something like:

#ifdef EXT_SHA256_H
#include EXT_SHA256_H
#else
...
#endif

Thanks.

**Comment by sfluhrer** [comment]
I assume that you're using your own implementation that's not OpenSSL?  That's fine; however what does your SHA256_CTX structure look like?

**Comment by alexJiangSierra** [comment]
My context is:

typedef struct {
  hash_state state;
} SHA256_CTX;

**Comment by sfluhrer** [comment]
I added this to the ext-sha256 branch; does those changes work for you?

**Comment by alexJiangSierra** [comment]
Fantastic!  Thanks so much.

**Comment by sfluhrer** [comment]
Ok, I pulled it into the main branch…

**Comment by sfluhrer** [comment]
Change merged into the main branch
