### ISSUE TITLE
Specific bug with H=10, aux_data_len=164 and num_threads=1 or 2

### ISSUE THREAD

**Issue by ttardieu** [cisco/hash-sigs#28]
It might be a very specific bug on the current master branch with the following parameters and configuration : 

- H=10 (the value of W and the number of levels does not seem to matter)
- aux_data is used with aux_data_len=164
- num_threads is set to 1 or 2 if pthread is used, or alternatively pthread is not used (so num_threads = 1)

In this case, the aux_data built by hss_generate_private_key is incomplete. All subsequent operation using it will give incorrect results.
I was not able to reproduce the bug with other settings.

**Comment by ttardieu** [comment]
While I'm there, the line
https://github.com/cisco/hash-sigs/blob/deef02bd88df558c1a88dd3db362891aab19b047/hss_aux.c#L120
is bad because there are 8 'f' instead of 7. But as this line is useless, it does not matter. Maybe we could remove it.

**Comment by sfluhrer** [comment]
I'm sorry, but I've been busy.  I'm not ghosting you; between being sick and extra work, I haven't had time to get to this.  I will, though...

**Comment by sfluhrer** [comment]
Ok, I committed both of them to the main branch.  I'll see if I can merge them into the 192 branch...
