### ISSUE TITLE
the value of 'public_key', 'len_public_key' are never used.

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [cisco/hash-sigs#4]
https://github.com/cisco/hash-sigs/blob/954485144168ef3a4a8f832cf1f8c047e7454b59/hss_keygen.c#L343

the value of 'public_key' is changed in expression 'public_key += size_hash', but the value is never used.
may be this expression is not useful at all? could we just delete it?

**Comment by sfluhrer** [comment]
It's there to be consistent with the previous lines that step through the public key.  It's not a performance issue - the compiler optimizer will just discard it...
